eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://192.168.179.129:8761/eureka/
      defaultZone: http:///192.168.179.129:8760/eureka/,http:///192.168.179.129:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: service-hi

