eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://peer1:7001/eureka/,http://peer2:7002/eureka/
server:
  port: 8762
spring:
  application:
    name: service-hi

